### ISSUE TITLE
Matplotlib version causes import error in colab

### ISSUE THREAD

**Issue by crlna16** [HelmholtzAI-Consultants-Munich/fg-clustering#12]
Very nice tutorial! 

I had a minor issue running the notebook `tutorial_FGC.ipynb` in Google Colab, where `plot_permutation_feature_importance` failed with an import error. It was resolved by downgrading matplotlib to `3.1.3` instead of `3.4.3`.

**Comment by hpelin** [comment]
Thanks for the comment! For this not to happen, the "Restart runtime" button has to be clicked (see step 2 in setup description). This is needed because Colab has matplotlib pre-installed but in the different version than the one we require. After clicking restart runtime in the output of the installation cell, you just continue running the cells and there should be no error.

**Comment by hpelin** [comment]
Thanks for the comment! For this not to happen, the "Restart runtime" button has to be clicked (see step 2 in setup description). This is needed because Colab has matplotlib pre-installed but in the different version than the one we require. After clicking restart runtime in the output of the installation cell, you just continue running the cells and there should be no error.
